# Generated by Django 5.2.3 on 2025-06-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='best_products/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Бургер месяца',
                'verbose_name_plural': 'Бургеры месяцы',
            },
        ),
    ]
